### ISSUE TITLE
Add Hyperlinks to the Partners Section

### ISSUE THREAD

**Issue by sheharyarIshfaq** [sheharyarIshfaq/cake-mania#1]
In the partner's section, there are images of popular brands like KFC, pizza hut, etc. Add hyperlinks to the images so that when someone clicks on them they are redirected to their website. The links should open in a new tab so use **target="_blank"** in the anchor tag.
Before starting to work, comment so that I can assign you.

**Comment by Foo-Maker** [comment]
Hey. 
I want to have a try on this Issue.

**Comment by sheharyarIshfaq** [comment]
I have assigned you the issue

**Comment by usmanghani-nc** [comment]
Hey, can you assign me this?

**Comment by sheharyarIshfaq** [comment]
@usmanghanidev  I have already assigned it to @Foo-Maker. You can check out this issue and contribute to that [Documentation Improvement](https://github.com/sheharyarIshfaq/The-News-Flux/issues/1#issue-1003722866)

**Comment by Foo-Maker** [comment]
Thank you @sheharyarIshfaq 

Can you please add the tag hacktoberfest to your repo?
Your repository is marked as "Project not participating".

**Comment by sheharyarIshfaq** [comment]
Great work @Foo-Maker 

I have added the hacktoberfest tag to the repository.
